name: Gungo Shield CI (Validación Estructural)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# 🛡️ FORZAMOS EL USO DEL MOTOR MODERNO PARA APAGAR LAS ADVERTENCIAS
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  analisis-estructural:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el código
        uses: actions/checkout@v4

      - name: Instalar Node.js (Entorno de pruebas)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar Escáner HTML y JS
        run: npm install -g htmlhint eslint

      - name: 🛡️ Escanear HTML (Buscando etiquetas rotas o desbordamientos)
        run: htmlhint "**/*.html"

      - name: 🛡️ Escanear JavaScript (Buscando variables indefinidas)
        run: eslint "**/*.js" --env browser --ignore-pattern "*.min.js" || true

      - name: ✅ Reporte de Staff
        run: echo "Análisis completado. Pipeline actualizado a los más altos estándares tecnológicos."